version: '3.8'

services:
  ssh-tunnel:
    build:
      context: .
      dockerfile: Dockerfile
    image: secure-ssh-tunnel-with-scheduled-updates
    container_name: secure-ssh-tunnel
    ports:
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./ssh_data:/home/tunnel_user/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Paris
